# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The 5th International Workshop on Automated Inductive Theorem Proving
email: wait.in.france@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Join us for the 5th workshop on Automated Inductive Theorem Proving. 
  Building on the success of previous editions - 1st in London (2013), 2nd in Gothenburg (2015), 3rd in Vienna (2016), and 4th in Amsterdam (2018) - 
  this year's workshop focuses on the latest advancements in both inductive and coinductive methods. 
  This event is a pivotal platform for researchers and practitioners to explore challenges and innovations in computational verification, 
  fostering collaboration across diverse verification methods like SMT, HOL, FOL, etc. 
  Don't miss this opportunity to engage with experts and shape the future of verification techniques.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: YutakangE
github_username:  WAIT2024

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
